[config]
layout = "recipes"
toc = true
colab = "https://colab.research.google.com/github/weaviate/recipes/blob/main/"

[[recipe]]
title = "Hybrid Search with Mistral"
notebook = "weaviate-features/hybrid-search/hybrid_search_mistral.ipynb"
tags = ["Hybrid Search", "Mistral"]

[[recipe]]
title = "RAG with Cohere on Amazon Bedrock and Weaviate on AWS Market place"
notebook = "integrations/cloud-hyperscalers/aws/RAG_Cohere_Weaviate_v4_client.ipynb"
tags = ["RAG", "Cohere", "AWS", "Amazon Bedrock"]

[[recipe]]
title = "How to use ColPali with Weaviate's Named Vectors"
notebook = "weaviate-features/multi-vector/NamedVectors-ColPali-POC.ipynb"
tags = ["ColPali", "Named Vectors"]

[[recipe]]
title = "How to Use Weaviate Embedding Service"
notebook = "weaviate-services/embedding-service/weaviate_embeddings_service.ipynb"
tags = ["Weaviate Embeddings", "Weaviate Cloud"]
featured = true

[[recipe]]
title = "Build A Weaviate Query Agent - The E-Commerce Assistant"
notebook = "weaviate-services/agents/query-agent-get-started.ipynb"
tags = ["Query Agent"]
agent = true
featured = true

[[recipe]]
title = "Build A Weaviate Transformation Agent"
notebook = "weaviate-services/agents/transformation-agent-get-started.ipynb"
tags = ["Transformation Agent"]
agent = true
featured = true

[[recipe]]
title = "Benchmarking Arctic 2.0 vs. Arctic 1.5 with Synthetic RAG Evals"
notebook = "weaviate-services/agents/transformation-agent-retrieval-benchmark.ipynb"
tags = ["Transformation Agent"]
agent = true
featured = true

[[recipe]]
title = "Weaviate Query Agent with Crew AI"
notebook = "integrations/llm-agent-frameworks/crewai/crewai-query-agent-as-tool.ipynb"
tags = ["Query Agent, Integration"]
integration = true

[[recipe]]
title = "Weaviate Query Agent with Haystack"
notebook = "integrations/llm-agent-frameworks/haystack/haystack-query-agent-tool.ipynb"
tags = ["Query Agent, Integration"]
integration = true

[[recipe]]
title = "Weaviate Query Agent with LlamaIndex"
notebook = "integrations/llm-agent-frameworks/llamaindex/agents/agent-workflow-with-weaviate-query-agent-.ipynb"
tags = ["Query Agent, Integration"]
integration = true